# Generated by Django 6.0.5 on 2026-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Café / Coffee Shop'), ('bakery', 'Bakery'), ('catering', 'Catering Company'), ('grocery', 'Grocery / Market'), ('other', 'Other')], default='restaurant', max_length=50)),
                ('street_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('frequency', models.CharField(blank=True, max_length=200)),
                ('food_types', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Business Partner Signup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('stripe', 'Stripe'), ('zelle', 'Zelle'), ('check', 'Check'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donation Record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_title', models.CharField(blank=True, max_length=300)),
                ('episode_type', models.CharField(choices=[('video', 'Video Interview'), ('written', 'Written Interview'), ('audio', 'Audio / Podcast')], default='video', max_length=20)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='podcast/')),
                ('published_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birthdate', models.DateField()),
                ('school', models.CharField(blank=True, max_length=200)),
                ('avail_days', models.CharField(blank=True, help_text='Comma-separated days', max_length=300)),
                ('avail_start', models.CharField(blank=True, help_text='General start time e.g. 09:00', max_length=10)),
                ('avail_end', models.CharField(blank=True, help_text='General end time e.g. 17:00', max_length=10)),
                ('future_dates', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Volunteer Signup',
                'ordering': ['-created_at'],
            },
        ),
    ]
